Fix compile error in Go 1.25
It fails with the following errors when compiling error:

```
../../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
```

The root cause is sonic library doesn't work well with the new Go
version. And it has been fixed in https://github.com/bytedance/sonic/issues/858,
which was included in sonic 1.14.0.